name: Update

on:
  workflow_dispatch:
    inputs:
      all_json:
        description: ''
        required: true
        default: '{}'
      area:
        description: ''
        required: true
        default: 'tokyo'
      commit_message:
        description: ''
        required: true
        default: ''

jobs:
  dispatch:
    name: Workflow dispatch events
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Create public/${{github.event.inputs.area}}/all.json
        run: echo '${{github.event.inputs.all_json}}' > ./public/${{github.event.inputs.area}}.json

 # './public/'+process.env.AREA+'/all.json'

      - name: Commit "${{github.event.inputs.commit_message}}"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "${{github.event.inputs.commit_message}}" -a
          git push origin main